export const top100Films = [
  { id: 1, label: 'The Shawshank Redemption' },
  { id: 2, label: 'The Godfather' },
  { id: 3, label: 'The Godfather: Part II' },
  { id: 4, label: 'The Dark Knight' },
  { id: 5, label: '12 Angry Men' },
  { id: 6, label: "Schindler's List" },
  { id: 7, label: 'Pulp Fiction' },
  { id: 8, label: 'The Lord of the Rings: The Return of the King' },
  { id: 9, label: 'The Good, the Bad and the Ugly' },
  { id: 10, label: 'Fight Club' },
  { id: 11, label: 'The Lord of the Rings: The Fellowship of the Ring' },
  { id: 12, label: 'Star Wars: Episode V - The Empire Strikes Back' },
  { id: 13, label: 'Forrest Gump' },
  { id: 14, label: 'Inception' },
  { id: 15, label: 'The Lord of the Rings: The Two Towers' },
  { id: 16, label: "One Flew Over the Cuckoo's Nest" },
  { id: 17, label: 'Goodfellas' },
  { id: 18, label: 'The Matrix' },
  { id: 19, label: 'Seven Samurai' },
  { id: 20, label: 'Star Wars: Episode IV - A New Hope' },
  { id: 21, label: 'City of God' },
  { id: 22, label: 'Se7en' },
  { id: 23, label: 'The Silence of the Lambs' },
  { id: 24, label: "It's a Wonderful Life" },
  { id: 25, label: 'Life Is Beautiful' },
  { id: 26, label: 'The Usual Suspects' },
  { id: 27, label: 'Léon: The Professional' },
  { id: 28, label: 'Spirited Away' },
  { id: 29, label: 'Saving Private Ryan' },
  { id: 30, label: 'Once Upon a Time in the West' },
  { id: 31, label: 'American History X' },
  { id: 32, label: 'Interstellar' },
  { id: 33, label: 'Casablanca' },
  { id: 34, label: 'City Lights' },
  { id: 35, label: 'Psycho' },
  { id: 36, label: 'The Green Mile' },
  { id: 37, label: 'The Intouchables' },
  { id: 38, label: 'Modern Times' },
  { id: 39, label: 'Raiders of the Lost Ark' },
  { id: 40, label: 'Rear Window' },
  { id: 41, label: 'The Pianist' },
  { id: 42, label: 'The Departed' },
  { id: 43, label: 'Terminator 2: Judgment Day' },
  { id: 44, label: 'Back to the Future' },
  { id: 45, label: 'Whiplash' },
  { id: 46, label: 'Gladiator' },
  { id: 47, label: 'Memento' },
  { id: 48, label: 'The Prestige' },
  { id: 49, label: 'The Lion King' },
  { id: 50, label: 'Apocalypse Now' },
  { id: 51, label: 'Alien' },
  { id: 52, label: 'Sunset Boulevard' },
  { id: 53, label: 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb' },
  { id: 54, label: 'The Great Dictator' },
  { id: 55, label: 'Cinema Paradiso' },
  { id: 56, label: 'The Lives of Others' },
  { id: 57, label: 'Grave of the Fireflies' },
  { id: 58, label: 'Paths of Glory' },
  { id: 59, label: 'Django Unchained' },
  { id: 60, label: 'The Shining' },
  { id: 61, label: 'WALL·E' },
  { id: 62, label: 'American Beauty' },
  { id: 63, label: 'The Dark Knight Rises' },
  { id: 64, label: 'Princess Mononoke' },
  { id: 65, label: 'Aliens' },
  { id: 66, label: 'Oldboy' },
  { id: 67, label: 'Once Upon a Time in America' },
  { id: 68, label: 'Witness for the Prosecution' },
  { id: 69, label: 'Das Boot' },
  { id: 70, label: 'Citizen Kane' },
  { id: 71, label: 'North by Northwest' },
  { id: 72, label: 'Vertigo' },
  { id: 73, label: 'Star Wars: Episode VI - Return of the Jedi' },
  { id: 74, label: 'Reservoir Dogs' },
  { id: 75, label: 'Braveheart' },
  { id: 76, label: 'M' },
  { id: 77, label: 'Requiem for a Dream' },
  { id: 78, label: 'Amélie' },
  { id: 79, label: 'A Clockwork Orange' },
  { id: 80, label: 'Like Stars on Earth' },
  { id: 81, label: 'Taxi Driver' },
  { id: 82, label: 'Lawrence of Arabia' },
  { id: 83, label: 'Double Indemnity' },
  { id: 84, label: 'Eternal Sunshine of the Spotless Mind' },
  { id: 85, label: 'Amadeus' },
  { id: 86, label: 'To Kill a Mockingbird' },
  { id: 87, label: 'Toy Story 3' },
  { id: 88, label: 'Logan' },
  { id: 89, label: 'Full Metal Jacket' },
  { id: 90, label: 'Dangal' },
  { id: 91, label: 'The Sting' },
  { id: 92, label: '2001: A Space Odyssey' },
  { id: 93, label: "Singin' in the Rain" },
  { id: 94, label: 'Toy Story' },
  { id: 95, label: 'Bicycle Thieves' },
  { id: 96, label: 'The Kid' },
  { id: 97, label: 'Inglourious Basterds' },
  { id: 98, label: 'Snatch' },
  { id: 99, label: '3 Idiots' },
  { id: 100, label: 'Monty Python and the Holy Grail' }
];
